version: 2

jobs:
  deploy-ui: &deploy-ui
    docker:
      - image: circleci/node:10
        environment:
          TERM: xterm
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npx firebase use --token $FIREBASE_DEPLOY_KEY $TARGET_ENVIRONMENT
      - run: npx firebase deploy -m "branch $CIRCLE_BRANCH - workflow $CIRCLE_WORKFLOW_ID - build $CIRCLE_BUILD_NUM" --token $FIREBASE_DEPLOY_KEY --non-interactive --only hosting:$TARGET_ENVIRONMENT

  deploy-develop:
    <<: *deploy-ui

  deploy-production:
    <<: *deploy-ui

workflows:
  version: 2

  test-deploy:
    jobs:
      - test
      - deploy-develop:
          context: aicura-website-develop
      - deploy-production:
          context: aicura-website-production
          filters:
            branches:
              only: production
